"""
Prompt templates for the LLM extraction engine.
All prompts enforce deterministic, structured JSON output.
"""

INTENT_CLASSIFICATION_PROMPT = """You are a structured data extraction engine.
Do not add commentary. Only output valid JSON. If uncertain, mark confidence low.

Classify the following user message into one or more intents from this list:
- expense
- income
- task
- event
- inventory_update
- care_log
- education_record
- property_transaction
- general_note

Message: {message}

Output JSON with this exact structure:
{{
  "intents": ["<intent1>", "<intent2>"],
  "primary_intent": "<most_likely_intent>",
  "confidence": <0.0 to 1.0>,
  "domain": "<finance|property|education|healthcare|inventory|personal_life|field_operations|general>"
}}"""

ENTITY_EXTRACTION_PROMPT = """You are a structured data extraction engine.
Do not add commentary. Only output valid JSON. If uncertain, mark confidence low.

Extract structured entities from this message for domain: {domain}, type: {intent_type}

Message: {message}
Today's date: {today}

Output JSON with this exact structure:
{{
  "domain": "{domain}",
  "type": "{intent_type}",
  "timestamp": "<ISO8601 datetime or null>",
  "entities": {{
    "merchant": "<string or null>",
    "category": "<string or null>",
    "tags": [],
    "notes": "<string or null>"
  }},
  "amount": <number or null>,
  "currency": "<3-letter ISO code, default GBP>",
  "description": "<concise human-readable summary>",
  "raw_input": "{message}",
  "confidence": <0.0 to 1.0>
}}

Rules:
- Extract amounts as numbers only (no currency symbols)
- Default currency to GBP unless specified
- If no date/time mentioned, set timestamp to null (system will use now)
- Category must be one of: Food & Drink, Groceries, Transport, Utilities, Shopping, Entertainment, Marketing, Health, Education, Rent, Salary, Freelance, Investment, Other
- Marketing = advertising spend (Facebook/Google/Instagram ads, ad campaigns, promotions)
- Groceries = supermarket trips (Tesco, Sainsbury's, Asda, Lidl, Aldi, etc.); Shopping = general/casual retail (Amazon, clothes, homeware)
- merchant: the shop, person, or entity involved
"""

CORRECTION_CLASSIFICATION_PROMPT = """Analyze the user's latest input within the context of recent chat logs and determine if they are correcting a previously logged item or creating a brand-new entry.

CORE RULES:
1. "CORRECTION_INTENT" occurs if the user explicitly or implicitly references an error in an absolute amount, a merchant name, a category, or wants to nullify a previous transaction.
2. The correction can apply to the absolute last entry, 2 turns ago, or a distinct historical entry mentioned by name/amount (e.g., "The Costa coffee thing").
3. If it is a new entry, output intent "RECORD_NEW".
4. If it is a correction, output intent "UPDATE_EXISTING" or "DELETE_EXISTING".

TAXONOMY TARGETS:
Available categories: [Food & Drink, Groceries, Transport, Shopping, Utilities, Entertainment, Health, Education, Rent, Income]

RECENT ENTRIES (most recent first):
{recent_entries}

USER INPUT: {message}

OUTPUT FORMAT:
Output ONLY raw, valid JSON. No markdown, no backticks, no prose.

If intent is "RECORD_NEW":
{{"intent": "RECORD_NEW", "payload": {{"amount": float, "description": "string", "category": "string", "type": "expense|income"}}}}

If intent is "UPDATE_EXISTING":
{{"intent": "UPDATE_EXISTING", "target_search_criteria": {{"approximate_old_amount": float|null, "old_description_keyword": "string|null"}}, "updates": {{"amount": float|null, "description": "string|null", "category": "string|null"}}}}

If intent is "DELETE_EXISTING":
{{"intent": "DELETE_EXISTING", "target_search_criteria": {{"approximate_old_amount": float|null, "old_description_keyword": "string|null"}}}}"""

DOCUMENT_PARSING_PROMPT = """Analyze the provided image and convert it into a structured transaction payload.

Document Classification & Parsing Rules:

1. Retail Receipts, Parking Tickets, and Toll Slips:
   - Locate the absolute final grand total after any discounts, itemizations, or surcharges.
   - Type: "expense". Category: "Groceries", "Food & Drink", "Shopping", or "Transport".

2. Commercial Invoices:
   - Inspect sender and recipient to verify cash-flow direction.
   - Type: "expense" if billed to you; "income" if generated by you for a client.
   - Category: "Utilities", "Shopping", or "Income".

3. Corporate Payslips and Government Letters:
   - Ignore gross income, tax codes, insurance deductions, reference strings. Isolate only the true net pay or tax refund amount.
   - Type: "income". Category: "Income".

4. Fintech and Bank App Screenshots:
   - Identify outgoing debit vs incoming credit from the layout. Extract the vendor name and transaction description.
   - Type: "expense" for outgoing; "income" for incoming. Category: map dynamically from the merchant.

5. Refund Receipts and Store Credit Slips:
   - Detect keywords like "REFUND", "CREDIT", or "RETURN". Convert the returned value into a NEGATIVE float to balance the ledger.
   - Type: "expense". Category: the original category of the returned item.

6. Handwritten Memos for Cash Transactions:
   - Use layout reasoning to parse handwritten numbers, currency indicators, and intention text.
   - Type: "expense" if cash spent; "income" if cash received. Category: from contextual keywords.

Output valid, raw JSON only. No markdown, no backticks, no prose. Exact schema:
{{
  "action": "RECORD_NEW",
  "type": "expense" | "income",
  "amount": float,
  "currency": "GBP" | "USD" | "EUR",
  "description": "string describing the merchant, transaction details, or document source",
  "category": "Groceries" | "Food & Drink" | "Shopping" | "Utilities" | "Income" | "Transport"
}}"""

LINE_ITEMS_PROMPT = """Extract EACH separate transaction from this message as a JSON array.
Output ONLY a raw JSON array — no markdown, no prose.

Each element:
{{"amount": number, "currency": "GBP|USD|EUR|NGN|GHS|KES|null", "description": "<short>", "type": "expense"|"income"}}

Rules:
- One element per distinct amount. Do NOT merge amounts or sum them.
- A currency stated once (e.g. "naira") applies to amounts that don't state their own.
- "description" = the few words explaining that specific amount.
- "withdrew/spent/paid/sent/bought" → expense; "received/earned/salary/refund" → income.

Examples:
"5000 for transport, 10000 for fees" -> [{{"amount":5000,"currency":null,"description":"transport","type":"expense"}},{{"amount":10000,"currency":null,"description":"fees","type":"expense"}}]

Message: {message}"""

QUERY_PLAN_PROMPT = """Convert the user's finance question into a JSON query plan.
Output ONLY raw JSON — no markdown, no prose.

Schema:
{{
  "metric": "spend_total" | "income_total" | "net" | "count" | "largest_expense" | "by_category",
  "timeframe": "today" | "week" | "month" | "year" | "last_month" | "all",
  "category": "<Food & Drink|Groceries|Transport|Utilities|Shopping|Entertainment|Marketing|Health|Education|Rent|null>",
  "merchant": "<merchant keyword or null>"
}}

Examples:
- "what's my biggest purchase this month" -> {{"metric":"largest_expense","timeframe":"month","category":null,"merchant":null}}
- "how many times did I buy coffee" -> {{"metric":"count","timeframe":"month","category":"Food & Drink","merchant":null}}
- "net this year" -> {{"metric":"net","timeframe":"year","category":null,"merchant":null}}

Question: {question}"""

QUERY_RESPONSE_PROMPT = """You are a financial assistant summarising ledger data.
Be concise and helpful. Format amounts with £ symbol. Use bullet points.

Query: {query}
Data: {data}

Provide a clear, brief summary."""

BUDGET_SUMMARY_PROMPT = """Summarise the following budget data concisely.
Show spent vs budget, and remaining amounts. Highlight overspent categories.

Period: {period}
Data: {data}"""
